fix: add missing IconFileInvoice import in Navigation
Error: ReferenceError: Can't find variable: IconFileInvoice

Solution: Added IconFileInvoice to the imports from @tabler/icons-react

This icon is used in the accountsSubItems submenu for the Invoices link.